### ISSUE TITLE
Waiting for the code!

### ISSUE THREAD

**Issue by Anikily** [DeepSceneSeg/EfficientPS#1]

**Comment by Raneee** [comment]
how long?

**Comment by avalada** [comment]
The paper is still under review. We plan to release the code within the next few months. Stay tuned!

**Comment by vladtamas** [comment]
Any news about this?

**Comment by ThanhPham1987** [comment]
waiting for

**Comment by avalada** [comment]
Thank you for your patience. The paper is still under review. We hope to release the code by the end of the year.

**Comment by Skywalker666666** [comment]
Marked

**Comment by Ankan1998** [comment]
Really excited to see the code. Heartiest thanks for doing such great work and we easily can use those model. Thank you

**Comment by avalada** [comment]
Dear All,

Thank you for your patience. We have received the first reviews for our EfficientPS paper and we are in the rebuttal phase at the moment. We will release the code after the final acceptance of the paper.

**Comment by jakubLangr** [comment]
Hi @avalada any updates?

**Comment by stormstoutzhang** [comment]
When?

**Comment by avalada** [comment]
We still are waiting for the reviews but we will release the code by the end of this month.

**Comment by avalada** [comment]
Code has been released
