### ISSUE TITLE
Performance / usage on "smaller" GPU

### ISSUE THREAD

**Issue by JimmysCheapJeep** [DeepSceneSeg/EfficientPS#10]
Hi there!
Thanks for sharing your code! :)
I tried to run the code,  but I don't have access to a Titan RTX as you proposed in the paper...   Obviously I'm running out of GPU memory... :)
I read the paper also, really nice work! 
Do you think there is a way to use your proposed procedure on "smaller", more widely used GPUs, or downscale the networks to process smaller images?
Thanks!

**Comment by mohan1914** [comment]
You can either switch to EfficientNet-B0 backbone that will require about 6-7GB of GPU memory for a single batch size while training. To do so in the config file in the backbone set type='tf_efficientnet_b0' (ln 6) and in the neck set  in_channels=[24, 40, 112, 1280] ln(12)
or reduce the image scale for training:
ln (140-141) in the config file, change resize img scale parameter to (1024, 512) and crop parameter to (512, 1024). Again the GPU memory required for a single batch size will be 6-7 GB. 
You can further combine both the options or reduce the img scale further for less GPU memory requirements.

I would suggest going with changing the backbone to avoid tweaking of Mask RCNN parameters.

**Comment by JimmysCheapJeep** [comment]
Hello!
Thanks a lot for your suggestions! We are going try it the way you mentioned...
