### ISSUE TITLE
pretrained weights links are down

### ISSUE THREAD

**Issue by windson87** [DeepSceneSeg/EfficientPS#16]
Dear author,

Thanks for sharing the model
I tried to download the pretrained weights, both links are not working for me..
it says 502 Bad Gateway

Could you please recheck the links? Thank :)

**Comment by avalada** [comment]
That was strange. It's back up now.

**Comment by windson87** [comment]
> That was strange. It's back up now.

thanks,. yes the links are working again  :)

**Comment by Wirg** [comment]
Hi ! 

Thanks for this project !
It seems like both links for pretrained weight are down again. :/

**Comment by avalada** [comment]
Sorry about that. The webserver is being migrated. It will be back up again in a few days.

**Comment by avalada** [comment]
The website is back up again.

**Comment by xinzi2018** [comment]
Thanks for this project!
It seems like both links for pre-trained weight are down again.

**Comment by avalada** [comment]
There are not down. Try with `wget http://panoptic.cs.uni-freiburg.de/static/models/efficientPS_cityscapes.zip`
