### ISSUE TITLE
What exactly does "hasInstance" do?

### ISSUE THREAD

**Issue by 95maddycode** [DeepSceneSeg/EfficientPS#19]
Dear authors,

What exactly does "hasInstance" do? When I experiment with putting different class labels on True/False, I get very different results. Can you elaborate a bit on how "hasInstances" is usually used, and when it should be set to False or True?

I though the following:
False = The label can only have one single instance
True = The label can have multiple instances
But when I set it to False, it seems like the model completely forgets about the label...  Is this nomal? 

Thanks in advance and kind regards

**Comment by mohan1914** [comment]
I am assuming you are talking in reference to the convert_cityscapes.py. The coco format dataset is only computed for classes that have instances. So if you put it false, it means that the corresponding class should not be part of the coco format dataset. 
In other words, hasInstances points out the classes that you want the instance head to learn. By extension defining what are the thing classes (hasInstances==True).
