### ISSUE TITLE
Why some pixel in output are black?

### ISSUE THREAD

**Issue by GabrieleGalimberti-GaleSelector** [DeepSceneSeg/EfficientPS#28]
Dear DeepSceneSeg Team,

in the output there are some pixel labeled as unknown class (for example in output of KITTI). 

![000064](https://user-images.githubusercontent.com/49124856/124432730-3a5b3c00-dd72-11eb-9e22-6b7ce8324bdc.png)

Why?

if it was wanted then why didn't you choose to label the semantic head in panoptic output when the class is labeled as unknown?

Thanks for your attention!

**Comment by mohan1914** [comment]
Sorry, I don't understand what you mean by 'if it was wanted then why didn't you choose to label the semantic head in panoptic output when the class is labeled as unknown?'
Assuming the output above is panoptic, I would suggest to follow cityscapes_save_predictions.py to generate white edges around each instance. 
If you don't want void in your final labels then you can treat the intermediate_mask (mmdet/models/effficientps/efficientPS.py) as your final panoptic output.
The additional processing step after computation of intermediate_mask is done to achieve a slightly higher PQ score by labeling most likely false positive regions as voids.

**Comment by GabrieleGalimberti-GaleSelector** [comment]
Okay, thank you for your reply.
You answered with what I needed.
I need to compute the PQ score and I needed the info about "labeling most likely false positive regions as voids".
