### ISSUE TITLE
Cannot download Pre-Trained Model for Cityscapes

### ISSUE THREAD

**Issue by Congdinh1801** [DeepSceneSeg/EfficientPS#29]
I tried to download your Pre-Trained Model for Cityscapes but it doesn't work. Can you double check if the link is still valid please? Thanks.

**Comment by avalada** [comment]
They do work. Maybe your browser is restricting the download. Please try, right click and "save link as..."

**Comment by Congdinh1801** [comment]
@avalada Your trick works for me. Thanks. I was trying to click on the link but nothing happened. Right click, "save link as...", and keep when it asks if you want to download the package are the steps for me.
