### ISSUE TITLE
pre-trained model (cityscape) classes missing? 

### ISSUE THREAD

**Issue by populusjade** [DeepSceneSeg/EfficientPS#36]
Hello ,thanks for sharing the pre-trained model. I want to ask if the pre-trained model (cityscape) detect other classes except classes like rider and car? I have run your code and the model can detect cars and people successfully, but other classes like road, vegetation are missing. As you provided results of other classes in cityscape-dataset, I asume the pre-trained model should be able to predict other classes. Could you explain a bit more. Thanks! :)

**Comment by mohan1914** [comment]
The pre-trained model ideally predicts all the classes (stuff + thing) for the dataset they are trained on. You can try the cityscapes_demo.py script in the tools folder to process random images. You can see in the image below (taken from the internet) train, bicycle classes are also being detected in addition to cars and people.
![test](https://user-images.githubusercontent.com/29768074/148992714-414dea3a-2c09-4ecc-bf4d-40de19e43863.jpg)
