### ISSUE TITLE
The download link for KITTI is broken, how could we get the KITTI annotations?

### ISSUE THREAD

**Issue by placeforyiming** [DeepSceneSeg/EfficientPS#9]
Thanks for this great work!

Is there any way to let us access the KITTI panoptic dataset provided in the website? 

The original link is broken.

**Comment by avalada** [comment]
Its fixed now http://panoptic.cs.uni-freiburg.de/#dataset

**Comment by placeforyiming** [comment]
Thank you very much! Hope your paper get accepted soon.

**Comment by avalada** [comment]
Thanks :)
